src/contracts/OnlyEntrypointGuard.sol
src/interfaces/IOnlyEntrypointGuard.sol

feat: implement safe guard

---

src/contracts/SafeEntrypoint.sol
src/interfaces/ISafeEntrypoint.sol

feat: deprecate getSafeTransactionHash() from address

---

src/contracts/SafeEntrypoint.sol
src/interfaces/ISafeEntrypoint.sol

feat: replace isQueued with queuedTransactionId

---

src/contracts/SafeEntrypoint.sol
src/interfaces/ISafeEntrypoint.sol
test/integration/BasicTest.t.sol

feat: add delay constants and index event params

---

src/contracts/SafeEntrypoint.sol

fix: start transaction IDs from 1

---

src/interfaces/ISafeEntrypoint.sol

docs: approval for queueing

---

src/contracts/factories/CappedTokenTransfersFactory.sol
src/interfaces/factories/ICappedTokenTransfersFactory.sol

feat: implement capped token factory

---

src/contracts/OnlyEntrypointGuard.sol
src/contracts/SafeEntrypoint.sol
src/interfaces/ISafeEntrypoint.sol

perf: optimize executeTransaction()

---

src/contracts/SafeEntrypoint.sol
src/contracts/factories/SafeEntrypointFactory.sol
src/interfaces/ISafeEntrypoint.sol
src/interfaces/factories/ISafeEntrypointFactory.sol
test/integration/BasicTest.t.sol

feat: immutable execution delays

---

src/contracts/OnlyEntrypointGuard.sol
src/contracts/SafeEntrypoint.sol
src/contracts/actions/AllowanceClaimor.sol
src/contracts/actions/CappedTokenTransfers.sol
src/contracts/actions/SimpleActions.sol
src/contracts/actions/SimpleTransfers.sol
src/contracts/factories/AllowanceClaimorFactory.sol
src/contracts/factories/SafeEntrypointFactory.sol
src/contracts/factories/SimpleActionsFactory.sol
src/contracts/factories/SimpleTransfersFactory.sol
src/interfaces/ISafeEntrypoint.sol

perf: revise gas efficiency

---

src/contracts/SafeEntrypoint.sol
src/interfaces/ISafeEntrypoint.sol

feat: remove unqueue method

---

src/contracts/SafeEntrypoint.sol
src/interfaces/ISafeEntrypoint.sol

feat: allow hash disapprovals

---

src/contracts/OnlyEntrypointGuard.sol
src/interfaces/IOnlyEntrypointGuard.sol

refactor: use SignatureDecoder and revise NatSpec in OnlyEntrypointGuard

---

src/contracts/SafeEntrypoint.sol
src/interfaces/ISafeEntrypoint.sol

feat: publicize disapprovedHashes

---

src/contracts/SafeEntrypoint.sol
src/interfaces/ISafeEntrypoint.sol
test/integration/BasicTest.t.sol

refactor: remove array param inputs

---

src/contracts/actions/CappedTokenTransfers.sol
src/interfaces/actions/IActionsBuilder.sol
src/interfaces/actions/ICappedTokenTransfers.sol

feat: make getactions view on capped transfer

---

src/contracts/SafeEntrypoint.sol

fix: encode arbitrary Action as Action[]

---

src/contracts/actions/SimpleTransfers.sol
test/integration/ethereum/IntegrationEthereumBase.sol
test/integration/ethereum/WonderlandTransfers.t.sol
test/integration/optimism/IntegrationOptimismBase.sol
test/integration/optimism/WonderlandTransfers.t.sol

test: wonderland transfers integration

---

src/contracts/actions/AllowanceClaimor.sol
src/contracts/actions/CappedTokenTransfers.sol
src/contracts/actions/SimpleActions.sol
src/contracts/actions/SimpleTransfers.sol
src/interfaces/actions/ISimpleActions.sol
src/interfaces/actions/ISimpleTransfers.sol

refactor: use abi.encodeCall for action data

---

test/unit/SimpleActionsFactory.t.sol
test/unit/SimpleActionsFactory.tree

test: add tests for SimpleActionsFactory

---

test/unit/SimpleTransfersFactory.t.sol
test/unit/SimpleTransfersFactory.tree

test: add tests for SimpleTransfersFactory

---

test/unit/SimpleActions.t.sol
test/unit/SimpleActions.tree

test: add tests for SimpleActions

---

test/unit/AllowanceClaimor.t.sol
test/unit/AllowanceClaimor.tree

test: add tests for AllowanceClaimor

---

test/unit/AllowanceClaimorFactory.t.sol
test/unit/AllowanceClaimorFactory.tree

test: add tests for AllowanceClaimorFactory

---

test/unit/SafeEntrypointFactory.t.sol
test/unit/SafeEntrypointFactory.tree

test: add tests for SafeEntrypointFactory

---

script/DeployEntrypoint.s.sol
src/contracts/OnlyEntrypointGuard.sol
test/integration/BasicTest.t.sol
test/unit/OnlyEntrypointGuard.t.sol
test/unit/OnlyEntrypointGuard.tree
test/unit/mocks/OnlyEntrypointGuardForTest.sol

feat: get `MULTI_SEND_CALL_ONLY` from SafeEntrypoint
